/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About_us: typeof import('./src/components/about_us.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Atravessar: typeof import('./src/components/atravessar.vue')['default']
    Barbeiro: typeof import('./src/components/barbeiro.vue')['default']
    Beijo: typeof import('./src/components/beijo.vue')['default']
    Cards: typeof import('./src/components/cards.vue')['default']
    Carro: typeof import('./src/components/carro.vue')['default']
    Casa_henrique: typeof import('./src/components/casa_henrique.vue')['default']
    Cozinhar: typeof import('./src/components/cozinhar.vue')['default']
    Doente: typeof import('./src/components/doente.vue')['default']
    Dormir: typeof import('./src/components/dormir.vue')['default']
    Endoscopia: typeof import('./src/components/endoscopia.vue')['default']
    Filmes: typeof import('./src/components/filmes.vue')['default']
    Gostar: typeof import('./src/components/gostar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Niver_fernando: typeof import('./src/components/niver_fernando.vue')['default']
    Pedido: typeof import('./src/components/pedido.vue')['default']
    Playlist: typeof import('./src/components/Playlist.vue')['default']
    Praia: typeof import('./src/components/praia.vue')['default']
    Primeiro_mes: typeof import('./src/components/primeiro_mes.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sad: typeof import('./src/components/sad.vue')['default']
    Site: typeof import('./src/components/site.vue')['default']
    Spoiler: typeof import('./src/components/spoiler.vue')['default']
    Stitch: typeof import('./src/components/stitch.vue')['default']
    Van_gogh: typeof import('./src/components/van_gogh.vue')['default']
  }
}
